src/lollidao.mainnet.ts, src/types.ts
Added LolliDAO addresses, based from 
https://halodao.atlassian.net/wiki/spaces/HALODAO/pages/148701381/LolliDAO+Mainnet
=> LolliDAO Addresses

package.json, src/arb.ts, src/arbTestnet.ts, src/kovan.ts, src/lollidao.mainnet.ts, src/mainnet.ts, src/matic.ts, src/rinkeby.ts, src/types.ts
Added more contract addresses required for amm-v2 FXPool deploy+deposit+withdraw scripts
=> Added more contract addresses required for amm-v2 FXPool deploy+deposit+withdraw scripts

src/arb.ts, src/arbTestnet.ts
Added tokens + oracles addresses for arb & arb testnet
For reviewers: need another set of eyes to double check & confirm arb (mainnet) tokens + oracle addresses
=> Added tokens + oracles addresses for arb & arb testnet

src/kovan.ts
For reference on this deployment:
https://halodao.atlassian.net/wiki/spaces/HALODAO/pages/158334988/Ethereum+Contracts
https://halodao.atlassian.net/wiki/spaces/HALODAO/pages/137330714/Rewards+AMM+mapping
=> feat: new EURS:USDC curve deployed on kovan

src/kovan.ts, src/types.ts
Added XSGD-USDC-indexUSDC credential
=> added starts credentials

src/kovan.ts, src/types.ts
=> added pool in start

src/kovan.ts
Change Strat#1 short name from XSGD to xSGD Thetanuts
=> rename strat#1 shortname

src/kovan.ts
=> add eurs-usdc pool

src/kovan.ts
=> add fxPools constant

src/kovan.ts
=> add new eurs/usdc fxpool

src/matic.ts
fakeXSGD - https://polygonscan.com/token/0x7112AE5d61eb28c7b00413882B59b7F796e2A505#readContract
fakeEURS - https://polygonscan.com/token/0xBb54874397Beb2Dd8673eb3B8Cd7C07d54bbd02D#readContract
=> feat: deploy new fake tokens on matic

src/kovan.ts
added new fxPool and Strat 1 address
=> added new fxPool and Strat 1 address

src/matic.ts
Adding lending market contracts and oracles
=> feat: polygon lending market support

src/matic.ts
Latest lending market deployment used in app.lending.xave.finance:
See 09/02/22 on https://halodao.atlassian.net/wiki/spaces/HALODAO/pages/177340417/Lending+Market+Polygon+Contracts
indexUSDC address to be confirmed:
https://polygonscan.com/token/0x35b51ff33be10a9a741e9c9d3f17585e4b7d15c0
=> feat: new lending market deployment (09/02/22) + indexUSDC address

src/arb.ts, src/kovan.ts, src/mainnet.ts, src/matic.ts, src/types.ts
- Adds balancerProtocolFee contract
=> Adds balancerProtocolFeeCollector contract

src/arbTestnet.ts, src/lollidao.mainnet.ts, src/rinkeby.ts, src/types.ts
- Updates type of balancerProtocolFeeCollector
=> Updates type of balancerProtocolFeeCollector

src/mainnet.ts, src/matic.ts
Please refer to the deployment logs below:
Polygon XSGD Thetanuts strat
https://polygonscan.com/address/0x3e02f6878D242FB6B85cC66dfc39e064CfFcfbd1 (link to polygonscan, lost the warp session for this deployment 😞)
Mainnet EURS Thetanuts strat
https://app.warp.dev/block/SgCw89W69O1Mi42CLD8Maz
=> feat: new thetanuts strat deployment on polygon & mainnet

src/goerli.ts
Double check the contract addresses on this page
https://halodao.atlassian.net/wiki/spaces/XAVE/pages/223576065/AMM+Goerli+Contracts
=> Add goerli AMM addresses

src/goerli.ts
Please check address here
https://halodao.atlassian.net/wiki/spaces/XAVE/pages/223051800/veXAV+Contracts+Goerli
=> Update XAV token to 0x4f2157aE2661e4312B8F2E458705fA5a9aeb3D46

src/goerli.ts
Contract addresses are also on this page: https://halodao.atlassian.net/wiki/spaces/XAVE/pages/230621185/Lending+Market+Goerli+Contracts
=> Add goerli LM contract addresses

package.json, src/matic.ts, src/types.ts
Added XSGD RewardsDistributor address for XSGD:USDC polygon pool
See https://halodao.atlassian.net/wiki/spaces/XAVE/pages/247889937/XSGD+Reward+Distributor+deployment+on+Polygon for deploy logs
=> Xsgd rewards distributor

package.json, src/matic.ts
Please refer to https://halodao.atlassian.net/browse/HDEV-1048 for context on why a new gauge is needed and the new gauge's contract address
=> feat: new gauge address for XSGD:USDC pool

src/avalanche.ts
Initial attempt: https://app.warp.dev/block/gU5oBRM4ww3ZK6vCzI2f94
=> feat: incomplete deployment

package.json, src/index.ts, src/sepolia.ts, src/types.ts
Confluence doc:
https://halodao.atlassian.net/wiki/spaces/XAVE/pages/280854529/AMM+Sepolia+Contracts
=> HDEV-1064-Sepolia-Support

src/avalanche.ts, src/matic.ts, src/types.ts
Added token + oracles addresses for VCHF, BRLA & VNXAU
See the ff docs for references:
- https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/283312129/VCHF+USDC+Deployment+Checklist
- https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/289406991/BRLA+USDC+Deployment+Checklist
- https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/289406977/VNXAU+USDC+Deployment+Checklist
=> feat: add new tokens + oracles

src/matic.ts
New deployment, see logs here https://app.warp.dev/block/UGywWt64zs3bcku3u40zOB
=> feat: new deployed xau->usd gram oracle

src/matic.ts
See below link for the deploy log:
https://app.warp.dev/block/kVEX8JkGpC4WurOuuuziPb
=> feat: redeploy VNXAU pool with the new XAU/USD gram oracle

package.json, src/avalanche.ts, src/matic.ts, src/types.ts
Polygon VCHF/USDC - https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/303169556/VCHF+USDC+Polygon+Deployment+Checklist
Polygon VEUR/USDC - https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/303169537/VEUR+USDC+Polygon+Deployment+Checklist
Avalanche VEUR:USDC - https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/303071233/VEUR+USDC+Avalanche+Deployment+Checklist
=> New FX pools deployment

package.json, src/avalanche.ts
For reference pls check https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/283312129/VCHF+USDC+Avalanche+Deployment+Checklist
=> feat: new VCHF oracle address on avalanche

package.json, src/avalanche.ts
Please refer to https://xc-labs.atlassian.net/wiki/spaces/XAVE/pages/283312148/Avalanche+VCHF+USDC
=> VCHF deployment

package.json, src/apothem.ts, src/arb.ts, src/arbTestnet.ts, src/avalanche.ts, src/goerli.ts, src/kovan.ts, src/lollidao.mainnet.ts, src/mainnet.ts, src/matic.ts, src/rinkeby.ts, src/sepolia.ts, src/types.ts
updated for fxpool deployer implementation 
updated with a newly deployed testnet contracts
=> 🛸 fxpool deployer types update

package.json, src/apothem.ts, src/arb.ts, src/arbTestnet.ts, src/avalanche.ts, src/goerli.ts, src/index.ts, src/kovan.ts, src/lollidao.mainnet.ts, src/mainnet.ts, src/matic.ts, src/rinkeby.ts, src/sepolia.ts, src/types.ts
Deployed new contract addresses
=> New sepolia addresses after fixing deploy script

package.json, src/apothem.ts, src/arb.ts, src/arbTestnet.ts, src/avalanche.ts, src/goerli.ts, src/kovan.ts, src/lollidao.mainnet.ts, src/mainnet.ts, src/matic.ts, src/rinkeby.ts, src/sepolia.ts, src/types.ts
- new pool addresses (moved old pools to `disabled`)
- add FXPoolMigrator address on Sepolia, Mainnet, Polygon & Avalanche
- expose all pool ids to clients
=> FXPool migration changes

src/avalanche.ts, src/types.ts
New addresses for baki support in fx pool deployemnt
=> 🍧 Baki support

package.json, src/matic.ts
Deployment log:  https://app.warp.dev/block/uYrK8cCzEa2WFwxRzKA3Rz
=> New generic usd oracle

package.json, src/arb.ts
Deployment log: https://app.warp.dev/block/mEtPv9ooRU0GyE6vzgzfHQ
=> feat: new MYRC:USD oracle

package.json, src/avalanche.ts, src/index.ts, src/katla.ts, src/types.ts
- Added AMM Rewards address in AVAX
- Added 80:20 XAV/USDC weighted pool in AVAX
=> Addresses for veXAV Avax
